### ISSUE TITLE
Auto-Stabilizaton/Auto-Charge Station

### ISSUE THREAD

**Issue by schineaj23** [Team2068/Muhkeighnzeigh#10]
Based on gyro, make the robot balance itself on the charge station.
Dependent on getting the chassis running.

**Comment by Ayidana-Aboraah** [comment]
This commit holds the start of the implementation before it's been tested: c7222fc52c05152af45d9dfd47cc2f6676543a64
Jaden, is the one primarily responsible for this.

**Comment by Ayidana-Aboraah** [comment]
Rewrite on a new branch, based on what Jaiden did, but with a few adjustments for the sake of autonomous (aka adjusting the drivetrain in general): d740b6267274263df074ef677424f2121f91516a

**Comment by schineaj23** [comment]
Closed with #19
